//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int idDetalle { get; set; }
        public int numFactura { get; set; }
        public int idVenta { get; set; }
        public int subTotal { get; set; }
        public int idProducto { get; set; }
        public int cantidad { get; set; }
    
        public virtual Venta Venta { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
