//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int numFactura { get; set; }
        public System.DateTime fecha { get; set; }
        public int IVA { get; set; }
        public int total { get; set; }
        public int numPago { get; set; }
        public Nullable<int> descuento { get; set; }
    
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual ModoPago ModoPago { get; set; }
    }
}
